// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtjrgmgfkekfifrszfmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0anJnbWdma2VrZmlmcnN6Zm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzY4NDMsImV4cCI6MjA2OTk1Mjg0M30.m3xRUAiwvofGaOwsgH9ti7XYIaPbjyny07--OKcDhrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});